### ISSUE TITLE
我的世界(Minecraft)Switch版通过DNS劫持实现连接自建云服务器

### ISSUE THREAD

**Issue by HowcanoeWang** [HowcanoeWang/HowcanoeWang.github.io#23]
https://www.sigmameow.com/blog/page.htmlid=21 

 官方逼死同人的最佳典范

**Comment by mlyxkj** [comment]
已经做了DNS，DNS无法连接上互联网，这是什么情况呢？

**Comment by mlyxkj** [comment]
用你的方法，没实现。采用了鸡排的方法实现了。
你的这个只是劫持了DNS，但是没有服务器列表。按照你的说明搭建，我网络都检测不通。会跳出叫认证的页面。跑是我开放的80端口上。
还是要运行这个：https://github.com/Pugmatt/BedrockConnect
提供服务器列表。

**Comment by HowcanoeWang** [comment]
> 已经做了DNS，DNS无法连接上互联网，这是什么情况呢？

> 用你的方法，没实现。采用了鸡排的方法实现了。
> 你的这个只是劫持了DNS，但是没有服务器列表。按照你的说明搭建，我网络都检测不通。会跳出叫认证的页面。跑是我开放的80端口上。
> 还是要运行这个：https://github.com/Pugmatt/BedrockConnect
> 提供服务器列表。

@mlyxkj 
既然本地DNS劫持可以实现联机，那么应该是出现在Linux云服务器配置上面，这个云服务器的主要目的是配置好之后，不需要每次玩之前都启动本地服务器+本地DNS劫持
1. 如果不是服务器大神，建议按照53给DNS和19132给MC服务器这么个端口配置，80端口是http端口很有可能被其他的占用了。
2. 确认不是用的境外服务器+移动网这种梦幻组合
3. 服务端运行DNS之后，不切到后台，然后用手机或另一台电脑链接，看看DNS的输出是什么，没有日志报错真的很难排查原因

**Comment by mlyxkj** [comment]
不好意思，事实上是我操作失误。失误的地方是DNS的服务文件和TXT文件。因为在B站没法下载，我用了知乎那边的。然后修改的TXT文件出错。
目前已经可以正常运行了。
对比了下，用鸡排的方法，可以自定义服务器地址和端口号。用你的这个方法，只能进一个服务器，只是进自己的服务器，所以还是用你这个方便。服务器启动后，2个命令就搞定。我把DNS服务和游戏都部署在同一个服务器上。UBUNTU 16.4，一开始部署我就没用18.4.
这个劫持方法，我去年7月份就在找了，一直没找到，这几天有空闲用谷歌搜一下就搜出来了。飞行感谢。我的NS，主机已经破解，为了测试这个，买了个正版的，后来又买一个LT，现在有三个了。
楼主可否加我QQ，一起交流学习。我的：2332196

**Comment by mlyxkj** [comment]
或者加我的QQ群。887086529

**Comment by zystzyt** [comment]
出现错误：
```javascript
Traceback (most recent call last):
  File "dns_server.py", line 69, in <module>
    ip = socket.gethostbyname(p.domain)
socket.gaierror: [Errno -5] No address associated with hostname
Traceback (most recent call last):
  File "dns_server.py", line 69, in <module>
    ip = socket.gethostbyname(p.domain)
socket.gaierror: [Errno -2] Name or service not known
```
刚学python，半天还都没琢磨透为什么会这样。

**Comment by HowcanoeWang** [comment]
> @zystzyt
> 出现错误：
> ```javascript
> Traceback (most recent call last):
>   File "dns_server.py", line 69, in <module>
>     ip = socket.gethostbyname(p.domain)
> socket.gaierror: [Errno -5] No address associated with hostname
> Traceback (most recent call last):
>   File "dns_server.py", line 69, in <module>
>     ip = socket.gethostbyname(p.domain)
> socket.gaierror: [Errno -2] Name or service not known
> ```
> 刚学python，半天还都没琢磨透为什么会这样。
> 
> 

应该不是python脚本的问题，这个脚本目前反馈下来都能正常运行，由于不知道你那边操作的所有步骤，我只能推测出来大概几个可能：
1. 参考这个issue，https://github.com/gamegos/cesi/issues/16，确认一下host.txt文件中，ip地址是否书写正确并且确保为当前服务器的地址(外网ip不是内网ip)，我猜大概率可能是这个问题？
2. 小概率可能是，云服务商的防火墙是否放开？每个服务商设置都不一样，而且对于网络类的背景知识要求比较高，如果真是这个问题，我可能也无法正确解答

另外，您给出的错误似乎没有复制完全？如果还不能解决问题，建议把所有报错输出完整的贴上

**Comment by zystzyt** [comment]
> @HowcanoeWang
> > @zystzyt
> > 出现错误：
> > ```javascript
> > Traceback (most recent call last):
> >   File "dns_server.py", line 69, in <module>
> >     ip = socket.gethostbyname(p.domain)
> > socket.gaierror: [Errno -5] No address associated with hostname
> > Traceback (most recent call last):
> >   File "dns_server.py", line 69, in <module>
> >     ip = socket.gethostbyname(p.domain)
> > socket.gaierror: [Errno -2] Name or service not known
> > ```
> > 刚学python，半天还都没琢磨透为什么会这样。
> > 
> > 
> 
> 应该不是python脚本的问题，这个脚本目前反馈下来都能正常运行，由于不知道你那边操作的所有步骤，我只能推测出来大概几个可能：
> 1. 参考这个issue，https://github.com/gamegos/cesi/issues/16，
> 确认一下host.txt文件中，ip地址是否书写正确并且确保为当前服务器的地址(外网ip不是内网ip)，我猜大概率可能是这个问题？
> 2. 小概率可能是，云服务商的防火墙是否放开？每个服务商设置都不一样，而且对于网络类的背景知识要求比较高，如果真是这个问题，我可能也无法正确解答
> 
> 另外，您给出的错误似乎没有复制完全？如果还不能解决问题，建议把所有报错输出完整的贴上

程序可以正常劫持host里的域名。
我看了下程序。觉得是因为有些域名无法解析到ip，所以才会提示找不到服务器。
服务器是怎么把接收到的域名解析成ip的？是不是switch-->MC服务器-->MC服务器里填的DNS（比如223.5.5.5）？

**Comment by HowcanoeWang** [comment]
> > @HowcanoeWang
> > > @zystzyt
> > > 出现错误：
> > > ```js
> > > Traceback (most recent call last):
> > >   File "dns_server.py", line 69, in <module>
> > >     ip = socket.gethostbyname(p.domain)
> > > socket.gaierror: [Errno -5] No address associated with hostname
> > > Traceback (most recent call last):
> > >   File "dns_server.py", line 69, in <module>
> > >     ip = socket.gethostbyname(p.domain)
> > > socket.gaierror: [Errno -2] Name or service not known
> > > ```
> > > 
> > > 
> > > 刚学python，半天还都没琢磨透为什么会这样。
> > 
> > 
> > 应该不是python脚本的问题，这个脚本目前反馈下来都能正常运行，由于不知道你那边操作的所有步骤，我只能推测出来大概几个可能：
> > 
> > 1. 参考这个issue，[https://github.com/gamegos/cesi/issues/16，](https://github.com/gamegos/cesi/issues/16%EF%BC%8C)
> >    确认一下host.txt文件中，ip地址是否书写正确并且确保为当前服务器的地址(外网ip不是内网ip)，我猜大概率可能是这个问题？
> > 2. 小概率可能是，云服务商的防火墙是否放开？每个服务商设置都不一样，而且对于网络类的背景知识要求比较高，如果真是这个问题，我可能也无法正确解答
> > 
> > 另外，您给出的错误似乎没有复制完全？如果还不能解决问题，建议把所有报错输出完整的贴上
> 
> 程序可以正常劫持host里的域名。
> 我看了下程序。觉得是因为有些域名无法解析到ip，所以才会提示找不到服务器。
> 服务器是怎么把接收到的域名解析成ip的？是不是switch-->MC服务器-->MC服务器里填的DNS（比如223.5.5.5）？

@zystzyt 嗯，主要的流程类似于

服务器用两个端口开了两个服务，x端口开了DNS解析服务，然后y端口开了MC服务

在Switch上面改完DNS之后，打开MC游戏->尝试寻找官方ip地址->连接到x端口的DNS解析->返回y端口的假官方ip(自己服务器的ip)->连接自己服务器ip的y端口MC服务->连上自己开设的服务器开始游戏

有可能是近期官方服务的ip发生了改变，文章中DNS配置出现了问题导致解析失败，建议先在`dns_server.py`报错的那个地方`ip = socket.gethostbyname(p.domain)`，上面增加一句`print(p.domain)`，看看输出了什么信息，如果和预想的一致，那么尝试去找一找官方DNS有没有变化吧

**Comment by HowcanoeWang** [comment]
@zystzyt 或者留下联系方式，总感觉这么评论交流太费劲了，得上手到服务器上面才能知道原因

**Comment by zystzyt** [comment]
> @zystzyt 或者留下联系方式，总感觉这么评论交流太费劲了，得上手到服务器上面才能知道原因

问题原因找到了，其实就是访问了些奇奇怪怪的网站
```(
错误: VERSION.BIND
Traceback (most recent call last):
  File "dns_server.py", line 69, in <module>
    ip = socket.gethostbyname(p.domain)
socket.gaierror: [Errno -2] Name or service not known

错误: com
Traceback (most recent call last):
  File "dns_server.py", line 69, in <module>
    ip = socket.gethostbyname(p.domain)
socket.gaierror: [Errno -5] No address associated with hostname

错误: 201.215.25.120.in-addr.arpa
Traceback (most recent call last):
  File "dns_server.py", line 69, in <module>
    ip = socket.gethostbyname(p.domain)
socket.gaierror: [Errno -2] Name or service not known
```
【错误：】后面的域名就是服务器无法解析报错的。
谢谢dalao的技术支持。
